apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gcptest
  name: gcptest
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcptest
  template:
    metadata:
      labels:
        app: gcptest
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/truckbase-348717/testrepo/gcptest:${SHORT_SHA}
        name: gcptest
  nodeSelector:
    cloud.google.com/gke-nodepool: default-pool
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gcptest
  name: gcptest
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gcptest
  sessionAffinity: None
  type: LoadBalancer